workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      groups:        
        - my-env-vars
      vars:
        FLUTTER_VERSION: stable
        XCODE_VERSION: "14.0"
        PROVISIONING_PROFILE_NAME: RideTideStride ios_app_store 1718997035
        BUNDLE_IDENTIFIER: com.example.rideTideStride
        DEVELOPMENT_TEAM: B6XGXJ6JZL
    scripts:
      - name: Set up CocoaPods
        script: |
          gem install cocoapods
          pod repo update
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install --repo-update
          pod update Firebase/CoreOnly
          cd ..
      - name: Create .env file in root directory
        script: |
          echo "OPENAI_API_KEY=${OPENAI_API_KEY}" > .env
      - name: Build iOS
        script: |
          flutter build ios --release
          xcodebuild -exportArchive -archivePath build/ios/iphoneos/Runner.xcarchive -exportPath build/ios/iphoneos/Runner -exportOptionsPlist ios/Runner/ExportOptions.plist -allowProvisioningUpdates
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        key_id: ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
        issuer_id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        api_key: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
        submit_to_testflight: true
        submit_to_app_store: true    
      email:
        recipients:
          - tpirozzini@gmail.com



