workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      groups:        
        - my-env-vars
      vars:
        FLUTTER_VERSION: stable
        XCODE_VERSION: "14.0"
    scripts:
      - name: Set up CocoaPods
        script: |
          gem install cocoapods
          pod repo update
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install --repo-update
          pod update Firebase/CoreOnly
          cd ..
      - name: Create .env file in root directory
        script: |
          echo "OPENAI_API_KEY=${OPENAI_API_KEY}" > .env
      - name: Build iOS
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa
    publishing:
      app_store_connect:
        api_key_id: ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
        issuer_id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        private_key: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
        submit_to_testflight: true
        submit_to_app_store: true
    publishing:
      email:
        recipients:
          - tpirozzini@gmail.com


