workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      groups:
        - my-env-vars # Reference the group name you created
      vars:
        FLUTTER_VERSION: stable
        XCODE_VERSION: "14.0" # Specify the required Xcode version
    scripts:
      - name: Set up CocoaPods
        script: |
          gem install cocoapods
          pod repo update
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install --repo-update
          pod update Firebase/CoreOnly
          cd ..
      - name: Create .env file
        script: |
          echo "API_URL=${API_URL}" > .env
          echo "API_KEY=${API_KEY}" >> .env
          mv .env ios/.env # Move the .env file to the ios directory
      - name: Build iOS
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa
    publishing:
      email:
        recipients:
          - tpirozzini@gmail.com

