workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      groups:        
        - my-env-vars             
    scripts:
      - name: Set up CocoaPods
        script: |
          gem install cocoapods
          pod repo update
      - name: Remove Podfile.lock
        script: |
          cd ios
          rm Podfile.lock
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install --repo-update
          pod update Firebase/Auth
          cd ..
      - name: Create .env file in root directory
        script: |
          echo "OPENAI_API_KEY=${OPENAI_API_KEY}" > .env              
      email:
        recipients:
          - tpirozzini@gmail.com





