import 'package:flutter/material.dart';

final activityIcons = {
  'Run': Icons.directions_run_outlined,
  'Ride': Icons.directions_bike_outlined,
  'Swim': Icons.pool_outlined,
  'Walk': Icons.directions_walk_outlined,
  'Hike': Icons.terrain_outlined,
  'AlpineSki': Icons.snowboarding_outlined,
  'BackcountrySki': Icons.snowboarding_outlined,
  'Canoeing': Icons.kayaking_outlined,
  'Crossfit': Icons.fitness_center_outlined,
  'EBikeRide': Icons.electric_bike_outlined,
  'Elliptical': Icons.fitness_center_outlined,
  'Handcycle': Icons.directions_bike_outlined,
  'IceSkate': Icons.ice_skating_outlined,
  'InlineSkate': Icons.ice_skating_outlined,
  'Kayaking': Icons.kayaking_outlined,
  'Kitesurf': Icons.kitesurfing_outlined,
  'NordicSki': Icons.snowboarding_outlined,
  'RockClimbing': Icons.terrain_outlined,
  'RollerSki': Icons.directions_bike_outlined,
  'Rowing': Icons.kayaking_outlined,
  'Snowboard': Icons.snowboarding_outlined,
  'Snowshoe': Icons.snowshoeing_outlined,
  'StairStepper': Icons.fitness_center_outlined,
  'StandUpPaddling': Icons.kayaking_outlined,
  'Surfing': Icons.surfing_outlined,
  'VirtualRide': Icons.directions_bike_outlined,
  'VirtualRun': Icons.directions_run_outlined,
  'WeightTraining': Icons.fitness_center_outlined,
  'Windsurf': Icons.surfing_outlined,
  'Workout': Icons.fitness_center_outlined,
  'Yoga': Icons.fitness_center_outlined,
  'Skateboard': Icons.skateboarding_outlined,
  'Motorbike': Icons.motorcycle_outlined,
  'Van': Icons.airport_shuttle_outlined,
};
